export const mangaData = [
    {
        Mangaid:    "1",
        MangaTitle:  "Solo leveling",
        MangaImg:   "https://avt.mkklcdnv6temp.com/30/a/17-1583496340.jpg",
        Mangadesc:  "This is just sample information used for testing",
        MangaAuthor: "Sample athor",
        MangaRating: "TBD how this is displayed",
        MangaViews: "420690",
        MangaTags: ["1","2","3"],
        Chapterurl: "https://manganelo.com/chapter/nk921730/chapter_15",
        ChapterImgId: "1",
        Chapterinfo:    "Chapter 1",
    },
    {
        Mangaid:    "2",
        MangaTitle:  "Tales Of Demons And Gods",
        MangaImg:   "https://avt.mkklcdnv6temp.com/19/v/1-1583464475.jpg",
        Mangadesc:  "This is just sample information used for testing",
        MangaAuthor: "Sample athor",
        MangaRating: "TBD how this is displayed",
        MangaViews: "420690",
        MangaTags: ["1","2","3"],
        Chapterurl: "https://manganelo.com/chapter/nk921730/chapter_15",
        ChapterImgId: "1",
        Chapterinfo:    "Chapter 1",
    },
    {
        Mangaid:    "3",
        MangaTitle:  "The Beginning After The End",
        MangaImg:   "https://avt.mkklcdnv6temp.com/48/q/17-1583497020.jpg",
        Mangadesc:  "This is just sample information used for testing",
        MangaAuthor: "Sample athor",
        MangaRating: "TBD how this is displayed",
        MangaViews: "420690",
        MangaTags: ["1","2","3"],
        Chapterurl: "https://manganelo.com/chapter/nk921730/chapter_15",
        ChapterImgId: "1",
        Chapterinfo:    "Chapter 1",
    },
    {
        Mangaid:    "4",
        MangaTitle:  "I am the Sorcerer King",
        MangaImg:   "https://avt.mkklcdnv6temp.com/35/c/18-1583498457.jpg",
        Mangadesc:  "This is just sample information used for testing",
        MangaAuthor: "Sample athor",
        MangaRating: "TBD how this is displayed",
        MangaViews: "420690",
        MangaTags: ["1","2","3"],
        Chapterurl: "https://manganelo.com/chapter/nk921730/chapter_15",
        ChapterImgId: "1",
        Chapterinfo:    "Chapter 1",
    }
]